language: node_js
node_js:
  - "10"
  - "12"
  - "13"

cache: yarn

script:
  # --color and --runInBand are necessary to ensure that `colors` work correctly
  - yarn test --coverage --runInBand --color
